/**
 * Task-related type definitions for the multi-agent orchestrator
 */

export enum TaskType {
  RESEARCH = "research",
  DESIGN = "design",
  CODE = "code",
  TEST = "test",
  DEBUG = "debug",
  DOCUMENT = "document",
  REVIEW = "review",
  DEPLOY = "deploy",
  MONITOR = "monitor",
  SECURITY_SCAN = "security_scan"
}

export enum TaskStatus {
  PENDING = "pending",
  IN_PROGRESS = "in_progress",
  COMPLETED = "completed",
  FAILED = "failed",
  BLOCKED = "blocked",
  CANCELLED = "cancelled"
}

export enum TaskPriority {
  LOW = 0,
  NORMAL = 1,
  HIGH = 2,
  CRITICAL = 3
}

/**
 * Core task interface representing a unit of work
 */
export interface Task {
  /** Unique task identifier */
  id: string;
  
  /** Type of task (research, code, test, etc.) */
  type: TaskType;
  
  /** Current status of the task */
  status: TaskStatus;
  
  /** Priority level for scheduling */
  priority: TaskPriority;
  
  /** IDs of tasks that must complete before this task */
  dependencies: string[];
  
  /** Task-specific data and parameters */
  data: Record<string, any>;
  
  /** ID of the agent assigned to this task */
  assignedAgent?: string;
  
  /** Result of task execution (populated after completion) */
  result?: TaskResult;
  
  /** When the task was created */
  createdAt: Date;
  
  /** Last update timestamp */
  updatedAt: Date;
  
  /** Optional human-readable description */
  description?: string;
  
  /** Estimated time to complete (in milliseconds) */
  estimatedDuration?: number;
  
  /** Actual time taken (populated after completion) */
  actualDuration?: number;
}

/**
 * Result of task execution
 */
export interface TaskResult {
  /** Whether the task completed successfully */
  success: boolean;
  
  /** Output data from task execution */
  data?: any;
  
  /** Error messages if task failed */
  errors?: string[];
  
  /** Generated artifacts (files, reports, etc.) */
  artifacts?: Artifact[];
  
  /** Performance and execution metrics */
  metrics?: TaskMetrics;
  
  /** Additional metadata */
  metadata?: Record<string, any>;
}

/**
 * Artifact generated by a task
 */
export interface Artifact {
  /** Unique artifact identifier */
  id: string;
  
  /** Type of artifact (file, report, diagram, etc.) */
  type: ArtifactType;
  
  /** File path or URL */
  path: string;
  
  /** Human-readable name */
  name: string;
  
  /** Optional description */
  description?: string;
  
  /** MIME type */
  mimeType?: string;
  
  /** Size in bytes */
  size?: number;
  
  /** Creation timestamp */
  createdAt: Date;
}

export enum ArtifactType {
  FILE = "file",
  REPORT = "report",
  DIAGRAM = "diagram",
  DOCUMENTATION = "documentation",
  TEST_RESULTS = "test_results",
  CODE = "code",
  CONFIG = "config",
  LOG = "log"
}

/**
 * Performance metrics for task execution
 */
export interface TaskMetrics {
  /** Execution time in milliseconds */
  executionTime: number;
  
  /** Memory usage in bytes */
  memoryUsage?: number;
  
  /** CPU usage percentage */
  cpuUsage?: number;
  
  /** Number of retries */
  retries?: number;
  
  /** Custom metrics */
  custom?: Record<string, number>;
}

/**
 * Task creation parameters
 */
export interface CreateTaskParams {
  type: TaskType;
  priority?: TaskPriority;
  dependencies?: string[];
  data: Record<string, any>;
  description?: string;
  estimatedDuration?: number;
}

/**
 * Task update parameters
 */
export interface UpdateTaskParams {
  status?: TaskStatus;
  priority?: TaskPriority;
  assignedAgent?: string;
  data?: Record<string, any>;
  result?: TaskResult;
}

